routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\QuestionSetController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\BulkQuestionController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   // return view('welcome');
    return view('index');
});


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/login', [App\Http\Controllers\LoginController::class, 'index'])->name('login');
Route::get('/change/password', [App\Http\Controllers\Auth\LoginController::class, 'changePasswordUI'])->name('changePasswordUI');
Route::post('/change-password', [App\Http\Controllers\Auth\LoginController::class, 'changePasswordConfirm'])->name('changePasswordConfirm');



/// Admin Routes
Route::get('/dashboard', [App\Http\Controllers\AdminController::class,'index'])->name('dashboard')->middleware('Admin');

//Question Set
Route::resource('question-set',QuestionSetController::class)->middleware('Admin');
Route::post('/question-set/updateQuestionSet/', [QuestionSetController::class,'updateQuestionSet'])->name('question-set.updateQuestionSet')->middleware('Admin');

//Questions
Route::resource('questions',QuestionsController::class)->middleware('Admin');
Route::get('/questionList/{question_set_id}', [QuestionsController::class,'listOfQuestions'])->name('questions.listOfQuestions')->middleware('Admin');
Route::get('/question-create/{question_set_id}', [QuestionsController::class,'createQuestion'])->name('questions.createQuestion')->middleware('Admin');
Route::get('/question-upload/{question_set_id}', [BulkQuestionController::class,'uploadQuestion'])->name('questions.uploadQuestion')->middleware('Admin');
Route::post('/question-import', [BulkQuestionController::class,'importQuestions'])->name('questions.importQuestions')->middleware('Admin');

/// Participants Route
Route::get('/participant', [App\Http\Controllers\ParticipantController::class,'index'])->name('participant')->middleware('Participant');
Route::get('/participantList', [App\Http\Controllers\ParticipantController::class,'participantList'])->name('participant.participantList')->middleware('Admin');
Route::get('/participant-profile-details/{participant_id}', [ParticipantController::class,'profileDetailsForAdmin'])->name('participant.profileDetailsForAdmin')->middleware('Admin');
Route::get('/profile', [ParticipantController::class,'profile'])->name('participant.profile')->middleware('Participant');
Route::get('/practice-test/{question_set_id}', [ParticipantController::class,'questions'])->name('participant.questions')->middleware('Participant');
Route::post('/practice-exam-submit', [ParticipantController::class,'exam_submit'])->name('participant.exam-submit')->middleware('Participant');
Route::get('/participant-history/{participant_id}', [ParticipantController::class,'historyForAdmin'])->name('participant.historyForAdmin')->middleware('Admin');
Route::get('/exam-history', [ParticipantController::class,'historyForParticipant'])->name('participant.historyForParticipant')->middleware('Participant');


Route::get('/exam-material/{question_set_id}', [ParticipantController::class,'examMaterial'])->name('participant.examMaterial')->middleware('Participant');

app/Models/Questions.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Questions extends Model
{
    use HasFactory;

    public function questionSet()
    {
    	return $this->belongsTo(QuestionSet::class, 'question_set_id');
    }


}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Questions;
use App\Models\QuestionSet;
use App\Http\Controllers\CommonController;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->common_class_obj = new CommonController();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }


    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validatedata = $request->validate([
            
            'correct_answer' => 'required|numeric|min:1'
        ]);

       
        $question_set_id = $request->question_set_id;

        if(($request->question_text == null ) && ($request->question_image == null)){
            return redirect()->route('questions.createQuestion',compact('question_set_id'))->with('error', 'Question should have text or image');
        }

        if(($request->option_1_text == null) && ($request->option_1_image == null)){
            return redirect()->route('questions.createQuestion',compact('question_set_id'))->with('error', 'Option 1 should have text or image');
        }

        if(($request->option_2_text == null ) && ($request->option_2_image == null )){
            return redirect()->route('questions.createQuestion',compact('question_set_id'))->with('error', 'Option 2 should have text or image');
        }

        if(($request->option_3_text == null ) && ($request->option_3_image == null )){
            return redirect()->route('questions.createQuestion',compact('question_set_id'))->with('error', 'Option 3 should have text or image');
        }

        if(($request->option_4_text == null ) && ($request->option_4_image == null )){
            return redirect()->route('questions.createQuestion',compact('question_set_id'))->with('error', 'Option 4 should have text or image');
        }

        if(($request->correct_answer <= 0) || ($request->correct_answer > 4)){
            return redirect()->route('questions.createQuestion',compact('question_set_id'))->with('error', 'Correct Answer should be between 1 to 4');
        }


        $question = new Questions();
        $question->question_set_id  = $question_set_id;

        $question->question_text = $request->question_text;
        
        if ($request->hasFile('question_image')) { // if image is not empty.

            $request->validate([
                'question_image' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            ]);

            $slug = Str::slug($request->question_image);

            $currentDate = Carbon::now()->toDateString();
            $imageQuestion = $slug . '-' . $currentDate . '-' . uniqid() . '.' .$request->question_image->getClientOriginalExtension();

            if (!file_exists('images/questions')) {
                mkdir('images/questions', 0777, true);
            }
            $request->question_image->move('images/questions', $imageQuestion);
        
            $question->question_image = $imageQuestion;
        
        }

        

        $question->option_1_text = $request->option_1_text;
        if ($request->hasFile('option_1_image')) { // if image is not empty.
            
            $request->validate([
                'option_1_image' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            ]);

            $slug = Str::slug($request->option_1_image);

            $currentDate = Carbon::now()->toDateString();
            $imageName1 = $slug . '-' . $currentDate . '-' . uniqid() . '.' .$request->option_1_image->getClientOriginalExtension();

            if (!file_exists('images/questions')) {
                mkdir('images/questions', 0777, true);
            }
            $request->option_1_image->move('images/questions', $imageName1);

            $question->option_1_image = $imageName1;
        }
        

        $question->option_2_text = $request->option_2_text;
        if ($request->hasFile('option_2_image')) { // if image is not empty.
            
            $request->validate([
                'option_2_image' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            ]);

            $slug = Str::slug($request->option_2_image);

            $currentDate = Carbon::now()->toDateString();
            $imageName2 = $slug . '-' . $currentDate . '-' . uniqid() . '.' .$request->option_2_image->getClientOriginalExtension();

            if (!file_exists('images/questions')) {
                mkdir('images/questions', 0777, true);
            }
            $request->option_2_image->move('images/questions', $imageName2);

            $question->option_2_image = $imageName2;
        }
        

        $question->option_3_text = $request->option_3_text;
        if ($request->hasFile('option_3_image')) { // if image is not empty.
           
            $request->validate([
                'option_3_image' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            ]);

            $slug = Str::slug($request->option_3_image);

            $currentDate = Carbon::now()->toDateString();
            $imageName3 = $slug . '-' . $currentDate . '-' . uniqid() . '.' .$request->option_3_image->getClientOriginalExtension();

            if (!file_exists('images/questions')) {
                mkdir('images/questions', 0777, true);
            }
            $request->option_3_image->move('images/questions', $imageName3);

            $question->option_3_image = $imageName3;
            
        }

        $question->option_4_text = $request->option_4_text;
        if ($request->hasFile('option_4_image')) { // if image is not empty.
           
            $request->validate([
                'option_4_image' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            ]);

            $slug = Str::slug($request->option_4_image);

            $currentDate = Carbon::now()->toDateString();
            $imageName4 = $slug . '-' . $currentDate . '-' . uniqid() . '.' .$request->option_4_image->getClientOriginalExtension();

            if (!file_exists('images/questions')) {
                mkdir('images/questions', 0777, true);
            }
            $request->option_4_image->move('images/questions', $imageName4);

            $question->option_4_image = $imageName4;
        }

        $question->correct_answer = $request->correct_answer;

        $question->created_by = Auth::user()->id;
        $question->updated_by = Auth::user()->id;


        $question->save();

        if ($question) {
            return redirect()->route('questions.listOfQuestions',compact('question_set_id'))->with('success', 'Question  Has Been Added Successfully');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Questions  $questions
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $question = Questions::findorFail($id);

        return view('questions.details', compact('question','id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Questions  $questions
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
       
        $question = Questions::findorFail($id);

        return view('questions.edit', compact('question','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Questions  $questions
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        //
        $validatedata = $request->validate([
            
            'correct_answer' => 'required|numeric|min:1'
        ]);

        $question = Questions::findorFail($id);
        $existing_question_image = $question->question_image;
        $existing_option_1_image = $question->option_1_image;
        $existing_option_2_image = $question->option_2_image;
        $existing_option_3_image = $question->option_3_image;
        $existing_option_4_image = $question->option_4_image;


        $question_set_id = $request->question_set_id;


        if(($request->question_text == null ) && ($request->question_image == null ) && ($question->question_image == null)){
            return redirect()->route('questions.listOfQuestions',compact('question_set_id'))->with('error', 'Question should have text or image');
        }

        if(($request->option_1_text == null ) && ($request->option_1_image == null )  && ($question->option_1_image == null)){
            return redirect()->route('questions.listOfQuestions',compact('question_set_id'))->with('error', 'Option 1 should have text or image');
        }

        if(($request->option_2_text == null ) && ($request->option_2_image == null )  && ($question->option_2_image == null)){
            return redirect()->route('questions.listOfQuestions',compact('question_set_id'))->with('error', 'Option 2 should have text or image');
        }

        if(($request->option_3_text == null ) && ($request->option_3_image == null )  && ($question->option_3_image == null)){
            return redirect()->route('questions.listOfQuestions',compact('question_set_id'))->with('error', 'Option 3 should have text or image');
        }

        if(($request->option_4_text == null ) && ($request->option_4_image == null )  && ($question->option_4_image == null)){

resources/views/questions/bulkUpload.blade.php
@extends('layouts.app_admin')
@section('title', 'Question')
    @push('css')


    @endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="col-12 section-header">
                <div class="col-6">
                    <h1> Upload Question</h1>
                </div>

            </div>
            @if ($errors->any())
            <div class="col-sm-12">
                <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                    @foreach ($errors->all() as $error)
                        <span>
                            <p>{{ $error }}</p>
                        </span>
                    @endforeach
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        @endif

        @include('flash-message')

            <div class="section-body">
                <div class="col-6">
                    <div class="card">
                        {{--  --}}
                        <div class="card-body">
                            <form method="POST" action="{{ route('questions.importQuestions') }}" id="editForm" enctype="multipart/form-data">
                                {{ method_field('POST') }}
                                {{ csrf_field() }}

                                <div class="form-group">
                                    <label>Upload File ( Excel Format)<code></code></label>
                                    <input type="file" name="upload_question" class="form-control form-control-lg" />
                                </div>
                               
                                <input type="hidden" name="question_set_id" id="question_set_id" class="form-control form-control-lg" readonly value="{{ $question_set_id }}"/>
                                <div class="card-footer text-right">
                                    <button class="btn btn-primary mr-1" type="submit">Submit</button>

                                </div>

                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>


        <!-- End -->
    </div>



@endsection

@section('extra-js')

@endsection

resources/views/questions/create.blade.php
@extends('layouts.app_admin')
@section('title', 'Question')
    @push('css')


    @endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="col-12 section-header">
                <div class="col-6">
                    <h1> Add Question</h1>
                </div>

            </div>
            @if ($errors->any())
            <div class="col-sm-12">
                <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                    @foreach ($errors->all() as $error)
                        <span>
                            <p>{{ $error }}</p>
                        </span>
                    @endforeach
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        @endif

        @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">
                        {{-- {{ route('product.store') }} --}}
                        <div class="card-body">
                            <form method="POST" action="{{ route('questions.store') }}" id="editForm" enctype="multipart/form-data">
                                {{ method_field('POST') }}
                                {{ csrf_field() }}

                                <div class="form-group">
                                    <label>Question (Text) <code></code></label>
                                    <input type="text" name="question_text" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Question (Image) <code></code></label>
                                    <input type="file" name="question_image" class="form-control form-control-lg" />
                                </div>


                                <div class="form-group">
                                    <label>Option 1 (Text) <code></code></label>
                                    <input type="text" name="option_1_text" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Option 1 (Image) <code></code></label>
                                    <input type="file" name="option_1_image" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Option 2 (Text) <code></code></label>
                                    <input type="text" name="option_2_text" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Option 2 (Image) <code></code></label>
                                    <input type="file" name="option_2_image" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Option 3 (Text) <code></code></label>
                                    <input type="text" name="option_3_text" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Option 3 (Image) <code></code></label>
                                    <input type="file" name="option_3_image" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Option 4 (Text) <code></code></label>
                                    <input type="text" name="option_4_text" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Option 4 (Image) <code></code></label>
                                    <input type="file" name="option_4_image" class="form-control form-control-lg" />
                                </div>

                                <div class="form-group">
                                    <label>Correct Answer <code></code></label>
                                    <input type="number" name="correct_answer" class="form-control form-control-lg" />
                                </div>

                               
                                <input type="hidden" name="question_set_id" id="question_set_id" class="form-control form-control-lg" readonly value="{{ $question_set_id }}"/>
                                <div class="card-footer text-right">
                                    <button class="btn btn-primary mr-1" type="submit">Submit</button>

                                </div>

                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>


        <!-- End -->
    </div>



@endsection

@section('extra-js')

@endsection

resources/views/questions/index.blade.php
@extends('layouts.app_admin')
@section('title', 'Question Set')
@push('css')


@endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">

            <div class="col-12 section-header">
                <div class="col-6">
                    <h1>Questions of-> {{ $questionSet->title }}</h1>
                </div>


                <div class="col-6 d-flex flex-row-reverse">
                    <a class="btn btn-primary" href="{{ route('questions.createQuestion', $questionSet->id) }}">
                        +Add New
                    </a>
                </div>
            </div>


            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table id="example" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Question (Text)</th>
                                            <th>Question (Image)</th>
                                            <th width="300px">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach ($questions as $key => $question)
                                            <tr>
                                                <td>{{ $key+1 }}</td>
                                                <td>
                                                    @if ($question->question_text != null)
                                                        {{ $question->question_text }}

                                                    @endif
                                                </td>
                                                <td >

                                                    @if ($question->question_image != null)
                                                        
                                                        <img alt="image" border=3 height="100px" width="150px" src="{{ asset('images/questions/' . $question->question_image) }}" />

                                                    @endif
                                                </td>

                                                <td>

                                                    <a class="btn btn-info"
                                                        href="{{ route('questions.show', $question->id) }}">
                                                        Details
                                                    </a>

                                                    <a class="btn btn-primary edit"
                                                        href="{{ route('questions.edit', $question->id) }}">
                                                        Edit
                                                    </a>


                                                    <form method="POST"
                                                        action="{{ route('questions.destroy', $question->id) }}"
                                                        style="display:inline">
                                                        {{ method_field('DELETE') }}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class=" btn-sm btn-danger"
                                                            onclick="return confirm('Confirm delete?')"><i
                                                                class="fa fa-trash-o" aria-hidden="true"></i>Delete

                                                        </button>
                                                    </form>
                                                </td>

                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>



    </div>

@endsection

@section('extra-js')
    <script>

    </script>
@endsection