routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\QuestionSetController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\BulkQuestionController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   // return view('welcome');
    return view('index');
});


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/login', [App\Http\Controllers\LoginController::class, 'index'])->name('login');
Route::get('/change/password', [App\Http\Controllers\Auth\LoginController::class, 'changePasswordUI'])->name('changePasswordUI');
Route::post('/change-password', [App\Http\Controllers\Auth\LoginController::class, 'changePasswordConfirm'])->name('changePasswordConfirm');



/// Admin Routes
Route::get('/dashboard', [App\Http\Controllers\AdminController::class,'index'])->name('dashboard')->middleware('Admin');

//Question Set
Route::resource('question-set',QuestionSetController::class)->middleware('Admin');
Route::post('/question-set/updateQuestionSet/', [QuestionSetController::class,'updateQuestionSet'])->name('question-set.updateQuestionSet')->middleware('Admin');

//Questions
Route::resource('questions',QuestionsController::class)->middleware('Admin');
Route::get('/questionList/{question_set_id}', [QuestionsController::class,'listOfQuestions'])->name('questions.listOfQuestions')->middleware('Admin');
Route::get('/question-create/{question_set_id}', [QuestionsController::class,'createQuestion'])->name('questions.createQuestion')->middleware('Admin');
Route::get('/question-upload/{question_set_id}', [BulkQuestionController::class,'uploadQuestion'])->name('questions.uploadQuestion')->middleware('Admin');
Route::post('/question-import', [BulkQuestionController::class,'importQuestions'])->name('questions.importQuestions')->middleware('Admin');

/// Participants Route
Route::get('/participant', [App\Http\Controllers\ParticipantController::class,'index'])->name('participant')->middleware('Participant');
Route::get('/participantList', [App\Http\Controllers\ParticipantController::class,'participantList'])->name('participant.participantList')->middleware('Admin');
Route::get('/participant-profile-details/{participant_id}', [ParticipantController::class,'profileDetailsForAdmin'])->name('participant.profileDetailsForAdmin')->middleware('Admin');
Route::get('/profile', [ParticipantController::class,'profile'])->name('participant.profile')->middleware('Participant');
Route::get('/practice-test/{question_set_id}', [ParticipantController::class,'questions'])->name('participant.questions')->middleware('Participant');
Route::post('/practice-exam-submit', [ParticipantController::class,'exam_submit'])->name('participant.exam-submit')->middleware('Participant');
Route::get('/participant-history/{participant_id}', [ParticipantController::class,'historyForAdmin'])->name('participant.historyForAdmin')->middleware('Admin');
Route::get('/exam-history', [ParticipantController::class,'historyForParticipant'])->name('participant.historyForParticipant')->middleware('Participant');


Route::get('/exam-material/{question_set_id}', [ParticipantController::class,'examMaterial'])->name('participant.examMaterial')->middleware('Participant');

app/Models/QuestionSet.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class QuestionSet extends Model
{
    use HasFactory;

    public function questions()
    {
    	return $this->hasMany(Questions::class);
    }


    public function participantData()
    {
    	return $this->hasMany(ParticipantHistory::class);
    }

    public function commentOfParticipant()
    {
    	return $this->hasMany(ParticipantComment::class);
    }
}

app/Http/Controllers/QuestionSetController.php
<?php

namespace App\Http\Controllers;

use App\Models\QuestionSet;
use App\Http\Controllers\CommonController;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class QuestionSetController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->common_class_obj = new CommonController();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $questionSets = QuestionSet::where('status', 1)->orderBy('id', 'DESC')->get();
        return view('questionSet.index', compact('questionSets'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $validatedata = $request->validate([
            'title' => 'required|max:50|min:5',
            // 'mark' => 'required|numeric|min:1',
            // 'duration' => 'required|numeric|min:1',
        ]);

        if (QuestionSet::where([['title', '=', $request->input('title')], ['status', '=', 1]])->first()) {
            return redirect()->route('question-set.index')->with('error', 'Question Set ' . $request->input('title') . ' Already in Use');
        }

        $questionSet = new QuestionSet();
        $questionSet->title = $request->title;
        // $questionSet->total_mark = $request->mark;
        // $questionSet->duration_time = $request->duration;
        $questionSet->created_by = Auth::user()->id;
        $questionSet->updated_by = Auth::user()->id;

        

        $questionSet->save();

        if ($questionSet) {
            return redirect()->route('question-set.index')->with('success', 'Question Set ' . $request->input('title') .' Has Been Added Successfully');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\QuestionSet  $questionSet
     * @return \Illuminate\Http\Response
     */
    public function show(QuestionSet $questionSet)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\QuestionSet  $questionSet
     * @return \Illuminate\Http\Response
     */
    public function edit(QuestionSet $questionSet)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\QuestionSet  $questionSet
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\QuestionSet  $questionSet
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $questionSet = QuestionSet::findorFail($id);
        $questionSet->status = 0;
        $questionSet->save();

        return redirect()->route('question-set.index')->with('success', 'Question Set ' . $questionSet->title .' Has Been Deleted Successfully');
    }

    public function updateQuestionSet(Request $request)
    {
        $validatedata = $request->validate([
            'title' => 'required|max:50|min:5',
            // 'mark' => 'required|numeric|min:1',
            // 'duration' => 'required|numeric|min:1',
        ]);

    $questionSet = QuestionSet::findorFail($request->id);
   
    
    $existingQuestionSet = QuestionSet::where([['title', '=', $request->input('title')], ['status', '=', 1]])->first();

    if (!empty($existingQuestionSet) && $existingQuestionSet->id  != $questionSet->id) {
        return redirect()->route('question-set.index')->with('error', 'Question Set ' . $request->input('title') . ' Already in Use');
    }

    $questionSet->title = $request->title;
    // $questionSet->total_mark = $request->mark;
    // $questionSet->duration_time =  $request->duration;
    $questionSet->updated_by = Auth::user()->id;


    $questionSet->save();

        if ($questionSet) {
            return redirect()->route('question-set.index')->with('success', 'Question Set ' . $request->input('title') .' Has Been Updated Successfully');
        }
    }
}

resources/views/questionSet/index.blade.php
@extends('layouts.app_admin')
@section('title', 'Question Set')
@push('css')


@endpush

@section('content')

    <!-- Main Content -->
    <div class="main-content">
        <section class="section">

            <div class="col-12 section-header">
                <div class="col-6">
                    <h1>Question Set</h1>
                </div>


                <div class="col-6 d-flex flex-row-reverse">
                    <button class="btn btn-primary" data-toggle="modal" data-target="#modal-part">
                        + Add New
                    </button>
                </div>
            </div>


            @if ($errors->any())
                <div class="col-sm-12">
                    <div class="alert  alert-warning alert-dismissible fade show" role="alert">
                        @foreach ($errors->all() as $error)
                            <span>
                                <p>{{ $error }}</p>
                            </span>
                        @endforeach
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            @endif

            @include('flash-message')

            <div class="section-body">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body p-0">
                            <div class="table-responsive">
                                <table id="example" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Title</th>
                                            {{-- <th>Mark</th>
                                            <th>Duration (Minute)</th> --}}
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($questionSets as $key => $questionSet)
                                            <tr>
                                                <td>{{ $key + 1 }}</td>
                                                <td>{{ $questionSet->title }}</td>
                                                {{-- <td>{{ $questionSet->total_mark }}</td>
                                                <td>{{ $questionSet->duration_time }}</td> --}}


                                                <td>

                                                    <a class="btn btn-primary edit"
                                                        onclick="changeModalData( '{{ $questionSet }}')"
                                                        data-toggle="modal" data-target="#modal-part2">
                                                        Edit
                                                    </a>

                                                    <form method="POST"
                                                        action="{{ route('question-set.destroy', $questionSet->id) }}"
                                                        style="display:inline">
                                                        {{ method_field('DELETE') }}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class=" btn-sm btn-danger"
                                                            onclick="return confirm('Confirm delete?')"><i
                                                                class="fa fa-trash-o" aria-hidden="true"></i>Delete

                                                        </button>
                                                    </form>

                                                    <a class="btn btn-info"
                                                        href="{{ route('questions.listOfQuestions', $questionSet->id) }}">
                                                        Questions
                                                    </a>

                                                    <a class="btn btn-primary edit"
                                                        href="{{ route('questions.uploadQuestion', $questionSet->id) }}">
                                                        Upload Question
                                                    </a>
                                                </td>

                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>

        <!-- Modal -->
        {{-- ADD Modal --}}
        <div class="modal fade" tabindex="-1" role="dialog" id="modal-part">
            <div class="modal-dialog" role="document">
                {{--  --}}
                <form method="POST" action="{{ route('question-set.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class=" modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Add Question Set</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <label>Title <code>*</code></label>
                                <input type="text" name="title" class="form-control form-control-lg" />
                            </div>
                            {{-- <div class="form-group">
                                <label>Total Mark <code>*</code></label>
                                <input type="number" name="mark" class="form-control form-control-lg" />
                            </div>
                            <div class="form-group">
                                <label>Duration (Minute)<code>*</code></label>
                                <input type="number" name="duration" class="form-control form-control-lg" />
                            </div> --}}

                        </div>
                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                Close
                            </button>
                            <button type="submit" class="btn btn-primary">
                                Save changes
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="modal fade" id="modal-part2" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">

                <form method="POST" action="{{ route('question-set.updateQuestionSet') }}">
                    {{ method_field('POST') }}
                    {{ csrf_field() }}
                    <div class=" modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Update Question Set</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">

                            <div class="modal-body">
                                <div class="form-group">
                                    <label>Title <code>*</code></label>
                                    <input type="text" name="title" id="title" class="form-control form-control-lg" />
                                </div>
                                {{-- <div class="form-group">
                                    <label>Total Mark <code>*</code></label>
                                    <input type="number" name="mark" id="mark" class="form-control form-control-lg" />
                                </div>
                                <div class="form-group">
                                    <label>Duration (Minute)<code>*</code></label>
                                    <input type="number" name="duration" id="duration"
                                        class="form-control form-control-lg" />
                                </div> --}}

                            </div>
                            <input type="hidden" name="id" id="id" class="form-control form-control-lg" readonly />
                        </div>

                        <div class="modal-footer bg-whitesmoke br">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                Close
                            </button>
                            <button type="submit" id="editProductHead" class="btn btn-primary">
                                Update
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('extra-js')
    <script>
        function changeModalData(questionSet) {
            console.log(questionSet);

            questionSet_data = JSON.parse(questionSet);

            document.getElementById("id").value = questionSet_data.id;
            document.getElementById("title").value = questionSet_data.title;
            // document.getElementById("mark").value = questionSet_data.total_mark;
            // document.getElementById("duration").value = questionSet_data.duration_time;


        }
    </script>
@endsection