routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\QuestionSetController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\BulkQuestionController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
   // return view('welcome');
    return view('index');
});


Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/login', [App\Http\Controllers\LoginController::class, 'index'])->name('login');
Route::get('/change/password', [App\Http\Controllers\Auth\LoginController::class, 'changePasswordUI'])->name('changePasswordUI');
Route::post('/change-password', [App\Http\Controllers\Auth\LoginController::class, 'changePasswordConfirm'])->name('changePasswordConfirm');



/// Admin Routes
Route::get('/dashboard', [App\Http\Controllers\AdminController::class,'index'])->name('dashboard')->middleware('Admin');

//Question Set
Route::resource('question-set',QuestionSetController::class)->middleware('Admin');
Route::post('/question-set/updateQuestionSet/', [QuestionSetController::class,'updateQuestionSet'])->name('question-set.updateQuestionSet')->middleware('Admin');

//Questions
Route::resource('questions',QuestionsController::class)->middleware('Admin');
Route::get('/questionList/{question_set_id}', [QuestionsController::class,'listOfQuestions'])->name('questions.listOfQuestions')->middleware('Admin');
Route::get('/question-create/{question_set_id}', [QuestionsController::class,'createQuestion'])->name('questions.createQuestion')->middleware('Admin');
Route::get('/question-upload/{question_set_id}', [BulkQuestionController::class,'uploadQuestion'])->name('questions.uploadQuestion')->middleware('Admin');
Route::post('/question-import', [BulkQuestionController::class,'importQuestions'])->name('questions.importQuestions')->middleware('Admin');

/// Participants Route
Route::get('/participant', [App\Http\Controllers\ParticipantController::class,'index'])->name('participant')->middleware('Participant');
Route::get('/participantList', [App\Http\Controllers\ParticipantController::class,'participantList'])->name('participant.participantList')->middleware('Admin');
Route::get('/participant-profile-details/{participant_id}', [ParticipantController::class,'profileDetailsForAdmin'])->name('participant.profileDetailsForAdmin')->middleware('Admin');
Route::get('/profile', [ParticipantController::class,'profile'])->name('participant.profile')->middleware('Participant');
Route::get('/practice-test/{question_set_id}', [ParticipantController::class,'questions'])->name('participant.questions')->middleware('Participant');
Route::post('/practice-exam-submit', [ParticipantController::class,'exam_submit'])->name('participant.exam-submit')->middleware('Participant');
Route::get('/participant-history/{participant_id}', [ParticipantController::class,'historyForAdmin'])->name('participant.historyForAdmin')->middleware('Admin');
Route::get('/exam-history', [ParticipantController::class,'historyForParticipant'])->name('participant.historyForParticipant')->middleware('Participant');


Route::get('/exam-material/{question_set_id}', [ParticipantController::class,'examMaterial'])->name('participant.examMaterial')->middleware('Participant');

resources/views/layouts/partial/admin/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; 2021
        <div class="bullet"></div>
    </div>
    <div class="footer-right">2.3.0</div>
</footer>

resources/views/layouts/partial/admin/head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>Trade Pro Canada</title>

<!-- Scripts -->


<!-- Fonts -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
<!-- <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" /> -->
<!-- CSS Libraries -->
<!-- <link rel="stylesheet" href="../node_modules/jqvmap/dist/jqvmap.min.css">
  <link rel="stylesheet" href="../node_modules/summernote/dist/summernote-bs4.css">
  <link rel="stylesheet" href="../node_modules/owl.carousel/dist/assets/owl.carousel.min.css">
  <link rel="stylesheet" href="../node_modules/owl.carousel/dist/assets/owl.theme.default.min.css"> -->

<!-- Template CSS -->
<link rel="stylesheet" href="{{ asset('../admin/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('../admin/css/components.css') }}">
<link rel="stylesheet" href="{{ asset('../admin/css/custom.css') }}">

resources/views/layouts/partial/admin/navbar.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
      <!-- <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li> -->
    </ul>
    <!--   <div class="search-element">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
      <button class="btn" type="submit"><i class="fas fa-search"></i></button>
      <div class="search-backdrop"></div>
      <div class="search-result">
        <div class="search-header">
          Histories
        </div>
        <div class="search-item">
          <a href="#">How to hack NASA using CSS</a>
          <a href="#" class="search-close"><i class="fas fa-times"></i></a>
        </div>
        <div class="search-item">
          <a href="#">Kodinger.com</a>
          <a href="#" class="search-close"><i class="fas fa-times"></i></a>
        </div>
        <div class="search-item">
          <a href="#">#Stock Management</a>
          <a href="#" class="search-close"><i class="fas fa-times"></i></a>
        </div>
        <div class="search-header">
          Result
        </div>
        <div class="search-item">
          <a href="#">
            <img class="mr-3 rounded" width="30" src="../assets/img/products/product-3-50.png" alt="product">
            oPhone S9 Limited Edition
          </a>
        </div>
        <div class="search-item">
          <a href="#">
            <img class="mr-3 rounded" width="30" src="../assets/img/products/product-2-50.png" alt="product">
            Drone X2 New Gen-7
          </a>
        </div>
        <div class="search-item">
          <a href="#">
            <img class="mr-3 rounded" width="30" src="../assets/img/products/product-1-50.png" alt="product">
            Headphone Blitz
          </a>
        </div>
        <div class="search-header">
          Projects
        </div>
        <div class="search-item">
            <a href="#">
              <div class="search-icon bg-danger text-white mr-3">
                <i class="fas fa-code"></i>
              </div>
              Stock Management Admin Template
            </a>
          </div>
          <div class="search-item">
            <a href="#">
              <div class="search-icon bg-primary text-white mr-3">
                <i class="fas fa-laptop"></i>
              </div>
              Create a new Homepage Design
            </a>
          </div>
      </div>
    </div> -->
  </form>
  <ul class="navbar-nav navbar-right">
    <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>
      <div class="dropdown-menu dropdown-list dropdown-menu-right">
        <div class="dropdown-header">Messages
          <div class="float-right">
            <a href="#">Mark All As Read</a>
          </div>
        </div>
        <div class="dropdown-list-content dropdown-list-message">
          <a href="#" class="dropdown-item dropdown-item-unread">
            <div class="dropdown-item-avatar">
              <img alt="image" src="{{ asset('admin/img/products/product-1-50.png') }}" class="rounded-circle">

              <div class="is-online"></div>
            </div>
            <div class="dropdown-item-desc">
              <b>Kusnaedi</b>
              <p>Hello, Bro!</p>
              <div class="time">10 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item dropdown-item-unread">
            <div class="dropdown-item-avatar">
              <img alt="image" src="../assets/img/avatar/avatar-2.png" class="rounded-circle">
            </div>
            <div class="dropdown-item-desc">
              <b>Dedik Sugiharto</b>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
              <div class="time">12 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item dropdown-item-unread">
            <div class="dropdown-item-avatar">
              <img alt="image" src="../assets/img/avatar/avatar-3.png" class="rounded-circle">
              <div class="is-online"></div>
            </div>
            <div class="dropdown-item-desc">
              <b>Agung Ardiansyah</b>
              <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <div class="time">12 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item">
            <div class="dropdown-item-avatar">
              <img alt="image" src="../assets/img/avatar/avatar-4.png" class="rounded-circle">
            </div>
            <div class="dropdown-item-desc">
              <b>Ardian Rahardiansyah</b>
              <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>
              <div class="time">16 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item">
            <div class="dropdown-item-avatar">
              <img alt="image" src="../assets/img/avatar/avatar-5.png" class="rounded-circle">
            </div>
            <div class="dropdown-item-desc">
              <b>Alfa Zulkarnain</b>
              <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
              <div class="time">Yesterday</div>
            </div>
          </a>
        </div>
        <div class="dropdown-footer text-center">
          <a href="#">View All <i class="fas fa-chevron-right"></i></a>
        </div>
      </div>
    </li>
    <li class="dropdown dropdown-list-toggle"><a href="/sales/create" class="nav-link nav-link-lg message-toggle beep"><i class="fas fa-luggage-cart"></i></a>
      <!-- <div class="dropdown-menu dropdown-list dropdown-menu-right">
          <div class="dropdown-header">Notifications
            <div class="float-right">
              <a href="#">Mark All As Read</a>
            </div>
          </div>
          <div class="dropdown-list-content dropdown-list-icons">
            <a href="#" class="dropdown-item dropdown-item-unread">
              <div class="dropdown-item-icon bg-primary text-white">
                <i class="fas fa-code"></i>
              </div>
              <div class="dropdown-item-desc">
                Template update is available now!
                <div class="time text-primary">2 Min Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-icon bg-info text-white">
                <i class="far fa-user"></i>
              </div>
              <div class="dropdown-item-desc">
                <b>You</b> and <b>Dedik Sugiharto</b> are now friends
                <div class="time">10 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-icon bg-success text-white">
                <i class="fas fa-check"></i>
              </div>
              <div class="dropdown-item-desc">
                <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                <div class="time">12 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-icon bg-danger text-white">
                <i class="fas fa-exclamation-triangle"></i>
              </div>
              <div class="dropdown-item-desc">
                Low disk space. Let's clean it!
                <div class="time">17 Hours Ago</div>
              </div>
            </a>
            <a href="#" class="dropdown-item">
              <div class="dropdown-item-icon bg-info text-white">
                <i class="fas fa-bell"></i>
              </div>
              <div class="dropdown-item-desc">
                Welcome to Stock Management template!
                <div class="time">Yesterday</div>
              </div>
            </a>
          </div>
          <div class="dropdown-footer text-center">
            <a href="#">View All <i class="fas fa-chevron-right"></i></a>
          </div>
        </div> -->
    </li>
    <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <img alt="image" src="{{ asset('admin/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
        <div class="d-sm-none d-lg-inline-block">Hi, {{ Auth::user()->first_name}}</div>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        {{-- <div class="dropdown-title">Logged in 5 min ago</div>
        <a href="pages/features-profile.html" class="dropdown-item has-icon">
          <i class="far fa-user"></i> Profile
        </a>
        <a href="pages/features-activities.html" class="dropdown-item has-icon">
          <i class="fas fa-bolt"></i> Activities
        </a>
        <a href="pages/features-settings.html" class="dropdown-item has-icon">
          <i class="fas fa-cog"></i> Settings
        </a> --}}
        <div class="dropdown-divider"></div>
        <a class="dropdown-item has-icon" href="{{ route('logout') }}" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
          <i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
          @csrf
        </form>
        {{--  --}}

        <a class="dropdown-item has-icon" href="{{ route('changePasswordUI') }}" >
<i class="fas fa-sign-out-alt"></i> {{ __('Change Password') }}
</a>
      </div>
    </li>
  </ul>
</nav>

resources/views/layouts/partial/admin/sidebar.blade.php
<div class="main-sidebar">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href="home">Trade Pro Canada</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="home"></a>
    </div>
    <ul class="sidebar-menu">
      
         
      

      <li class="nav-item dropdown">
        <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-cubes"></i> <span>Question Set</span></a>
        <ul class="dropdown-menu">
          <li>
            
            <a class="nav-link" href="{{ route('question-set.index') }}">Practice Test</a>
            
          </li>
        </ul>

      </li>

      <li class="nav-item dropdown">
        <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-cubes"></i> <span>Participants</span></a>
        <ul class="dropdown-menu">
          <li>
            
            <a class="nav-link" href="{{ route('participant.participantList') }}">Participant List</a>
            
          </li>
        </ul>

      </li>


  </aside>

</div>